# 机器人
bot:
    enable: true # 是否启用内置机器人
    welcome: 回复 /help 查询指令 # 接受好友或有人进入群聊时响应的消息，留空则不响应
    revoke: 撤回了寂寞？ # 撤回消息时响应的消息，留空则不响应
    managers: [] # 管理员名单
    blackList: [] # 黑名单，禁止使用机器人
    whiteList: [] # 白名单，禁止其他人使用机器人
    hostedRooms: # 托管群列表，允许自动拉人
        - mask: 1 # 群标记，用于生成加群指令
          name: 测试群一 # 群名称，在指令说明中使用
          roomId: 12345123@chatroom # 群 Id，可以从网页后台获取
          welcome: 欢迎加入云食堂，请先阅读群公告 # 单独指定此群的欢迎词，留空使用全局设置
        - mask: 2
          name: 测试群二
          roomId: 43434111@chatroom

# 大模型
llm:
    historyNum: 20 # 历史消息数量
    roleContext: | # 定义模型扮演的身份
        你是由OpenTDP开发的群助手，必须使用尽可能少的字数回答接下来的所有问题。
    models: # 模型列表
        - name: gemini # 模型标记，用于生成模型切换指令
          provider: google # 服务商，支持 [google, openai, xunfei]
          endpoint: https://googai.173371.xyz # 留空则使用官方接口，仅 google 和 openai 支持自定义
          model: gemini-pro # 模型，必须和服务商对应
          key: API-KEY # 密钥，必须和服务商对应
        - name: gpt
          provider: openai
          endpoint: https://chatai.173371.xyz
          model: gpt-3.5-turbo
          key: API-KEY
        - name: spark
          provider: xunfei
          model: v3
          key: APP-ID,API-KEY,API-SECRET

# 运行日志
log:
    dir: logs # 日志目录
    level: info # 日志级别
    target: stdout # 日志输出方式

# Web 服务
web:
    address: 127.0.0.1:7600 # 监听地址
    swagger: true # 是否启用 OpenApi 文档
    token: "" # 使用 Token 验证请求

# Wcf 服务
wcf:
    address: 127.0.0.1:7601 # Rpc 监听地址
    wechatAuto: true # 是否跟随启停微信
    msgPrinter: false # 是否打印收到的消息
