# 运行日志
Log:
    Dir: logs # 存储目录
    Level: info # 记录级别，debug|info|warn|error
    Target: stdout # 输出方式，both|file|null|stdout|stderr

# Wcf 服务
Wcf:
    Address: 127.0.0.1:7601 # 监听地址
    MsgStore: true # 是否存储收到的消息
    MsgPrint: false # 是否打印收到的消息
    WcfBinary: wcf.exe # 注入工具路径，留空则不注入
    WeChatAuto: true # 是否自动启停微信，关闭微信后才能注入

# Web 服务
Web:
    Address: 127.0.0.1:7600 # 监听地址
    Swagger: true # 是否启用 Api 在线文档
    Token: "" # 使用 Token 验证请求，留空则不验证
    Webhook: "" # 消息推送地址，留空则不启用
