httpd:
    address: 127.0.0.1:7600
    token: ""
    swag: true
logger:
    dir: logs
    level: info
    target: stdout
robot:
   enable: true
   friendWelcome: 回复 /help 查询指令
wcf:
    address: 127.0.0.1:10080
    sdkLibrary: wcferry/libs/sdk.dll
    wechatAuto: true
    msgPrinter: false
