# 机器人
bot:
    enable: true # 是否启用内置机器人
    friendWelcome: 回复 /help 查询指令 # 添加好友后自动回复
    roomAddList: # 群组列表
        - id: 38699745819@chatroom
          name: OpenTDP 开发群
        - id: 17907657671@chatroom
          name: OpenTDP 闲聊群

# REST 接口
httpd:
    address: 127.0.0.1:7600 # api 监听地址
    token: "" # 使用 token 验证请求
    swag: true # 启用 OpenApi 文档

# 运行日志
logger:
    dir: logs # 日志目录
    level: info # 日志级别
    target: stdout # 日志输出方式

# WeChat Ferry
wcf:
    address: 127.0.0.1:10080 # rpc 监听地址
    sdkLibrary: wcferry/libs/sdk.dll # sdk 依赖库
    wechatAuto: true # 自动启停微信
    msgPrinter: false # 打印收到的消息
